backend:
  name: git-gateway
  branch: develop # Branch to update (master by default)

media_folder: "assets/images" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - { label: "Published", name: "published", widget: boolean }
      - { label: "Year", name: "year", widget: string }
      - { label: "Featured", name: "featured", widget: boolean }
      - { label: "Title", name: "title", widget: string }
      - { label: "Client", name: "client", widget: string }
      - { label: "Brief Description", name: "brief_description", widget: string, hint: "One sentence, no period at the end" }
      - { label: "SEO Description", name: "seo_description", widget: string }
      - { label: "Fellow", name: "fellow", widget: "string" } # To use a relation widget, we need to convert fellows to a markdown-based collection
      - label: Blogs
        name: blogs
        widget: list
        required: false
        fields:
          - { label: "Title", name: "title", widget: string, required: true }
          - { label: "Link", name: "link", widget: string, hint: "Full URL (https://www.azavea.com/blog/2017/08/02/how-to-calculate-location-accessibility-with-accessmod-5/)",  required: true }
      - { label: "Featured Image", name: "featured_image", widget: image }
      - label: Images
        name: images
        widget: list
        required: false
        fields:
          - { label: "Image", name: "image", widget: image }
      - { label: "Project description", name: "body", widget: markdown, required: true }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "_data/pages/about.yml"
        fields:
          - { label: "Date", name: "date", widget: string, hint: "[Month] [YYYY]", required: true }
          - { label: "Description", name: "description", widget: string, hint: "One sentence, no period at the end",  required: true }
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Dates"
        name: "dates"
        file: "_data/dates.yml"
        fields:
          - label: Dates
            name: dates
            widget: list
            required: false
            fields:
              - { label: "Date", name: "date", widget: string, hint: "[Month] [YYYY]", required: true }
              - { label: "Description", name: "description", widget: string, hint: "One sentence, no period at the end",  required: true }
      - label: "Categories"
        name: "categories"
        file: "_data/categories.yml"
        fields:
          - label: Categories
            name: categories
            widget: list
            required: false
            fields:
              - { label: "Name", name: "name", widget: string, required: true }
              - { label: "Slug", name: "slug", widget: string, required: true }
      - label: "Fellows"
        name: "fellows"
        file: "_data/fellows.yml"
        fields:
          - label: Fellows
            name: fellows
            widget: list
            required: false
            fields:
              - { label: "Name", name: "name", widget: string, required: true }
              - { label: "Slug", name: "slug", widget: string, required: true }
              - { label: "Year", name: "year", widget: number, required: true }
              - { label: "Info", name: "info", widget: number, required: true }
              - { label: "Image", name: "image", widget: image, required: true }
      - label: "Mentors"
        name: "mentors"
        file: "_data/mentors.yml"
        fields:
          - label: Mentors
            name: mentors
            widget: list
            required: false
            fields:
              - { label: "Full Name", name: "name", widget: string, required: true }
              - { label: "First Name", name: "shortName", widget: string, required: true }
              - { label: "Profile", name: "profile", widget: string, required: true, hint: "Full url from Azavea site (https://www.azavea.com/about/teammate/[...])" }
              - { label: "Image", name: "image", widget: image, required: true }

      # - name: "categories"
      #   label: "Categories"
      #   folder: "_categories"
      #   create: true
      #   fields:
      #     - { label: "Category Name", name: "title", widget: string }
      #     - { label: "Icon", name: "icon", widget: string }
      # - name: "regions"
      #   label: "Regions"
      #   folder: "_regions"
      #   create: true
      #   fields:
      #     - { label: "Region Name", name: "title", widget: string }
      #     - { label: "Unique ID", name: "id", widget: string }
      # - name: "pois"
      #   label: "Point of Interest"
      #   folder: "_pois"
      #   create: true
      #   fields:
      #     - { label: "Unique", name: "title", widget: string }
      #     - { label: "Heading (Popup)", name: "heading", widget: string }
      #     - { label: "Description (Popup)", name: "body", widget: markdown, buttons: ["bold", "italic", "link"], required: false }
      #     - { label: "Icon", name: "icon", widget: string }
      #     - { label: "Important", name: "important", widget: "boolean", default: true }
      #     - label: "Related Parcel"
      #       name: "related"
      #       widget: "relation"
      #       collection: "slides"
      #       required: false
      #       searchFields: ["title"]
      #       valueField: "ltmid"
      #       displayFields: ["title"]
      #     - { label: "Geometry", name: "geojson", widget: geojson }
      # - name: "slides"
      #   label: "Slides"
      #   folder: "_slides"
      #   create: true
      #   fields:
      #     - { label: "Parcel Name", name: "title", widget: string }
      #     - { label: "Geometry", name: "geojson", widget: geojson }
      #     - { label: "Body", name: "body", widget: markdown, buttons: ["bold", "italic", "link"] }
      #     - { label: "LTMID", name: "ltmid", widget: string }
      #     - label: "Region"
      #       name: "region"
      #       widget: "relation"
      #       collection: "regions"
      #       required: true
      #       searchFields: ["title"]
      #       valueField: "id"
      #       displayFields: ["title"]
      #     - { label: "Size", name: "size", widget: number, required: false }
      #     - { label: "Image", name: "image", widget: image, required: false }
      #     - { label: "Related URL", name: "related", widget: string, required: false }
      #     - { label: "Google Maps", name: "googlemaps", widget: string, required: false }
      #     - label: Categories
      #       name: categories
      #       widget: list
      #       required: false
      #       fields:
      #         - label: "Category"
      #           name: "category"
      #           widget: "relation"
      #           collection: "categories"
      #           searchFields: ["title"]
      #           valueField: "icon"
      #           displayFields: ["title"]
